# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 15:03
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Campaign = apps.get_model("froide_campaign", "Campaign")
    CampaignPage = apps.get_model("froide_campaign", "CampaignPage")
    for campaign in Campaign.objects.all():
        page = CampaignPage.objects.create(
            title=campaign.title,
            slug=campaign.slug,
            description=campaign.description,
            public=campaign.public,
        )
        page.campaigns.add(campaign)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("froide_campaign", "0008_campaignpage"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
