# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_campaign', '0010_campaign_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationobject',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
