# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_campaign", "0011_auto_20161018_1918"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationobject",
            name="resolution_link",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="informationobject",
            name="resolution_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="informationobject",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
    ]
