# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_campaign', '0012_auto_20161020_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationobject',
            name='context',
            field=models.JSONField(blank=True),
        ),
    ]
