# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_campaign", "0014_auto_20170615_1113"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="paused",
            field=models.BooleanField(default=False),
        ),
    ]
