# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models

import froide_campaign.models
import froide_campaign.storage


class Migration(migrations.Migration):

    dependencies = [
        ("froide_campaign", "0016_auto_20180125_1603"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campaignpage",
            options={
                "permissions": (("can_use_campaigns", "Can use campaigns"),),
                "verbose_name": "Campaign page",
                "verbose_name_plural": "Campaign pages",
            },
        ),
        migrations.AlterField(
            model_name="campaignpage",
            name="embed",
            field=models.FileField(
                blank=True,
                storage=froide_campaign.storage.OverwriteStorage(),
                upload_to=froide_campaign.models.get_embed_path,
            ),
        ),
    ]
