# Generated by Django 2.2.4 on 2020-03-13 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('froide_campaign', '0018_auto_20180402_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRequestsCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='froide_campaign_campaignrequestscmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('campaign_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='froide_campaign.CampaignPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
