# Generated by Django 3.0.8 on 2020-08-24 14:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_campaign', '0023_fill_foirequests_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='provider',
            field=models.CharField(blank=True, choices=[('', 'froide_campaign.providers.base.BaseProvider')], max_length=40),
        ),
        migrations.AddField(
            model_name='campaign',
            name='provider_kwargs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
