# Generated by Django 3.0.8 on 2020-08-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_campaign", "0024_auto_20200824_1614"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigncmsplugin",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        )
    ]
