# Generated by Django 3.0.8 on 2020-09-21 08:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_campaign", "0026_auto_20200902_1657"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigncmsplugin",
            name="request_extra_text",
            field=models.TextField(blank=True),
        )
    ]
