# Generated by Django 3.0.8 on 2020-09-23 18:58

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_campaign", "0027_auto_20200921_1007"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="froide_campaign.Campaign",
                    ),
                ),
            ],
        ),
    ]
