# Generated by Django 3.0.8 on 2020-11-02 12:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_campaign", "0029_auto_20201027_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationobject",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
