# Generated by Django 3.0.8 on 2020-12-02 16:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('froide_campaign', '0033_auto_20201130_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignProgressCMSPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='froide_campaign_campaignprogresscmsplugin', serialize=False, to='cms.CMSPlugin')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='froide_campaign.Campaign')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
