# Generated by Django 3.1.4 on 2021-02-04 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("froide_campaign", "0039_auto_20210204_1319"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informationobject",
            name="_subtitle",
        ),
        migrations.RemoveField(
            model_name="informationobject",
            name="_title",
        ),
    ]
