# Generated by Django 3.1.6 on 2021-02-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("froide_campaign", "0042_move_campaign_translation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="_description",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="_slug",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="_subject_template",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="_template",
        ),
        migrations.RemoveField(
            model_name="campaign",
            name="_title",
        ),
    ]
