# Generated by Django 3.1.4 on 2021-02-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("froide_campaign", "0043_auto_20210208_1537"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="informationobject",
            name="tags",
        ),
    ]
