# Generated by Django 3.2.8 on 2021-11-17 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foirequest", "0053_alter_foimessage_email_headers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("froide_campaign", "0046_auto_20211117_1134"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="foirequest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="foirequest.foirequest",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="questionaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="froide_campaign.questionaire",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="timestamp",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
