# Generated by Django 3.2.8 on 2021-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("froide_campaign", "0047_auto_20211117_1311"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["position", "id"]},
        ),
        migrations.AlterModelOptions(
            name="report",
            options={"get_latest_by": "timestamp", "ordering": ("-timestamp",)},
        ),
        migrations.AddField(
            model_name="questionaire",
            name="multiple_reports",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="data_type",
            field=models.CharField(
                blank=True,
                choices=[("", "Text"), ("choices", "Choices"), ("integer", "Integer")],
                default="",
                max_length=20,
            ),
        ),
    ]
