# Generated by Django 4.2.16 on 2025-04-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0035_auto_20230822_2208_squashed_0036_auto_20240311_1028"),
        ("froide_campaign", "0049_alter_answer_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "",
                        "froide_campaign.providers.informationobject.InformationObjectProvider",
                    ),
                    ("amenity", "froide_campaign.providers.amenity.AmenityProvider"),
                    (
                        "publicbody",
                        "froide_campaign.providers.publicbody.PublicBodyProvider",
                    ),
                    (
                        "amenity_local",
                        "froide_campaign.providers.amenity_local.AmenityLocalProvider",
                    ),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="campaigncmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="campaignprogresscmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="campaignquestionairecmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
        migrations.AlterField(
            model_name="campaignrequestscmsplugin",
            name="cmsplugin_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                related_name="%(app_label)s_%(class)s",
                serialize=False,
                to="cms.cmsplugin",
            ),
        ),
    ]
