# Generated by Django 5.2.10 on 2026-05-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_campaign", "0050_alter_campaign_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informationobject",
            name="questionaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="information_objects",
                to="froide_campaign.questionaire",
                verbose_name="Questionaire",
            ),
        ),
    ]
